;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	TeX-insert-backslash
	TeX-insert-dollar
	TeX-insert-sub-or-superscript
	beginning-of-visual-line
	comment-or-uncomment-region-or-line
	completion-backward-delete-char
	cua--prefix-override-handler
	end-of-visual-line
	indent-for-tab-command
	kill-visual-line
	sgml-slash
	))

(setq mc/cmds-to-run-once
      '(
	cua-paste
	mark-whole-buffer
	mouse-set-region
	))
